/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.dealer_returns;

import controllers.DIMOPartsReturnController;
import controllers.DealerReturnController;
import controllers.OtherSupplierReturnController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author shdinesh.99
 */
public class DealerReturnPanel extends javax.swing.JPanel {

    private DefaultTableModel returnMOdel,totalOtherSupplierRetuns,otherSupplierRetuDtm,DIMOStockPrtsreturnDtm;
 private TableRowSorter<TableModel> partsSorter,partsSorterOther;
  private SimpleDateFormat sdf;
    /**
     * Creates new form DealerReturnPanel
     */
    public DealerReturnPanel() {
        initComponents();
        returnMOdel = (DefaultTableModel) tblAllReturns.getModel();
        partsSorter = new TableRowSorter<TableModel>(totalOtherSupplierRetuns);
        sdf = new SimpleDateFormat("yyyy-MM-dd");
        otherSupplierRetuDtm = (DefaultTableModel) tblOtherSupplierReturns.getModel();
        DIMOStockPrtsreturnDtm=(DefaultTableModel)tblDIMOStockPartReturn.getModel();
        partsSorterOther = new TableRowSorter<TableModel>(otherSupplierRetuDtm);
        
        try {
            loadAllDealerReturns();
            loadAllOtherSupplierReturns(0);
            loadAllDIMOStockPartReturn(0);
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }
    }

    public void loadAllDealerReturns() throws ClassNotFoundException, SQLException {
        ResultSet rst = DealerReturnController.loadAllDealerReturns();
        String tableRow[] = new String[12];
        returnMOdel.setRowCount(0);
        while (rst.next()) {
            for (int i = 0; i <= 11; i++) {
                tableRow[i] = rst.getString(i + 1);
            }

            returnMOdel.addRow(tableRow);
        }
    }
     public void loadAllOtherSupplierReturns(int supplier) throws ClassNotFoundException, SQLException {
        ResultSet rst = OtherSupplierReturnController.getOtherSupplierReturns(supplier);
        int rowCount = otherSupplierRetuDtm.getRowCount();
        Object tableRow[] = new Object[8];
        if (rowCount >= 0) {
            otherSupplierRetuDtm.setRowCount(0);
        }
        while (rst.next()) {
            for (int i = 0; i < 8; i++) {
                tableRow[i] = rst.getString(i + 1);
                
            }
            otherSupplierRetuDtm.addRow(tableRow);
        }
    }
     public void loadAllDIMOStockPartReturn(int supplier) throws ClassNotFoundException, SQLException {
        ResultSet rst =DIMOPartsReturnController.getDIMOPartsStockRetdetail(supplier);
        int rowCount = DIMOStockPrtsreturnDtm.getRowCount();
        Object tableRow[] = new Object[9];
        if (rowCount >= 0) {
            DIMOStockPrtsreturnDtm.setRowCount(0);
        }
        while (rst.next()) {
            for (int i = 0; i < 9; i++) {
                tableRow[i] = rst.getString(i + 1);
                
            }
           DIMOStockPrtsreturnDtm.addRow(tableRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllReturns = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOtherSupplierReturns = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDIMOStockPartReturn = new javax.swing.JTable();
        btnAccepted = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        tblAllReturns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblAllReturns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "return id", "deliver order id", "Return note No.", "Return date", "Return time", "Rep sccepted date", "Rep accepted time", "Rep", "Admin accepted date", "Admin accepted time", "rep_ret_id", "admin_ret_id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAllReturns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAllReturnsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAllReturns);
        if (tblAllReturns.getColumnModel().getColumnCount() > 0) {
            tblAllReturns.getColumnModel().getColumn(0).setMinWidth(0);
            tblAllReturns.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblAllReturns.getColumnModel().getColumn(0).setMaxWidth(0);
            tblAllReturns.getColumnModel().getColumn(1).setMinWidth(0);
            tblAllReturns.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblAllReturns.getColumnModel().getColumn(1).setMaxWidth(0);
            tblAllReturns.getColumnModel().getColumn(8).setMinWidth(0);
            tblAllReturns.getColumnModel().getColumn(8).setPreferredWidth(0);
            tblAllReturns.getColumnModel().getColumn(8).setMaxWidth(0);
            tblAllReturns.getColumnModel().getColumn(9).setMinWidth(0);
            tblAllReturns.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblAllReturns.getColumnModel().getColumn(9).setMaxWidth(0);
            tblAllReturns.getColumnModel().getColumn(11).setMinWidth(0);
            tblAllReturns.getColumnModel().getColumn(11).setPreferredWidth(0);
            tblAllReturns.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        jTabbedPane1.addTab("DIMO Invoice Returns", jPanel1);

        tblOtherSupplierReturns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Return ID", "Item ID", "Item Part No", "Return Quantity", "Buying Price", "Return Date", "Return Time", "Return Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOtherSupplierReturns);
        if (tblOtherSupplierReturns.getColumnModel().getColumnCount() > 0) {
            tblOtherSupplierReturns.getColumnModel().getColumn(0).setMinWidth(0);
            tblOtherSupplierReturns.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblOtherSupplierReturns.getColumnModel().getColumn(0).setMaxWidth(0);
            tblOtherSupplierReturns.getColumnModel().getColumn(1).setMinWidth(0);
            tblOtherSupplierReturns.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblOtherSupplierReturns.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Other Supplier Returns", jPanel2);

        tblDIMOStockPartReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ReturnID", "ItemID", "StockID", "Item Part No", "Return Quantity", "Buying Price", "Added Date", "Added Time", "Return Amount", "Selected"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDIMOStockPartReturn);
        if (tblDIMOStockPartReturn.getColumnModel().getColumnCount() > 0) {
            tblDIMOStockPartReturn.getColumnModel().getColumn(0).setMinWidth(0);
            tblDIMOStockPartReturn.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblDIMOStockPartReturn.getColumnModel().getColumn(0).setMaxWidth(0);
            tblDIMOStockPartReturn.getColumnModel().getColumn(1).setMinWidth(0);
            tblDIMOStockPartReturn.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblDIMOStockPartReturn.getColumnModel().getColumn(1).setMaxWidth(0);
            tblDIMOStockPartReturn.getColumnModel().getColumn(2).setMinWidth(0);
            tblDIMOStockPartReturn.getColumnModel().getColumn(2).setPreferredWidth(0);
            tblDIMOStockPartReturn.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        btnAccepted.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAccepted.setText("Accepted");
        btnAccepted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptedActionPerformed(evt);
            }
        });

        btnReject.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReject.setText("Rejected");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAccepted, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccepted, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DIMO Stock Parts  Return", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DealerReturnController.getAllRepAcceptedReturns();
           // DealerReturnController.getAllAdminAcceptedReturns();    //2015-10-19
            loadAllDealerReturns();
        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int selectedRow = tblAllReturns.getSelectedRow();
            int deliverOrderID = Integer.parseInt(tblAllReturns.getValueAt(selectedRow, 1).toString());
            String returnNoteNo = tblAllReturns.getValueAt(selectedRow, 2).toString();
            int returnID = Integer.parseInt(tblAllReturns.getValueAt(selectedRow, 0).toString());
            int repReturnID = Integer.parseInt(tblAllReturns.getValueAt(selectedRow, 10).toString());
            int adminReturnID = Integer.parseInt(tblAllReturns.getValueAt(selectedRow, 11).toString());

            ReturnParts rp = new ReturnParts(null, true, deliverOrderID, returnID, repReturnID, adminReturnID, returnNoteNo);
            rp.setVisible(true);
            loadAllDealerReturns();
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Please select a row", "Wrong index", JOptionPane.WARNING_MESSAGE);
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (SQLException sQLException) {
        }

//ReturnParts(java.awt.Frame parent, boolean modal, int deliverOrderID, int dealerReturnID, int repReturnID, int adminReturnID, String returnNoteNo) 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblAllReturnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllReturnsMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                int selectedRow = tblAllReturns.getSelectedRow();
                int deliverOrderID = Integer.parseInt(tblAllReturns.getValueAt(selectedRow, 1).toString());
                String returnNoteNo = tblAllReturns.getValueAt(selectedRow, 2).toString();
                int returnID = Integer.parseInt(tblAllReturns.getValueAt(selectedRow, 0).toString());
                int repReturnID = Integer.parseInt(tblAllReturns.getValueAt(selectedRow, 10).toString());
                int adminReturnID = Integer.parseInt(tblAllReturns.getValueAt(selectedRow, 11).toString());

                ReturnParts rp = new ReturnParts(null, true, deliverOrderID, returnID, repReturnID, adminReturnID, returnNoteNo);
                rp.setVisible(true);
                loadAllDealerReturns();
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(this, "Please select a row", "Wrong index", JOptionPane.WARNING_MESSAGE);
            } catch (ClassNotFoundException classNotFoundException) {
            } catch (SQLException sQLException) {
            }
        }
    }//GEN-LAST:event_tblAllReturnsMouseClicked

    private void btnAcceptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptedActionPerformed
                for(int i=0;i<DIMOStockPrtsreturnDtm.getRowCount();i++) {
                    if(Boolean.parseBoolean(DIMOStockPrtsreturnDtm.getValueAt(i, 9)+"")== true){
                    int retID = Integer.parseInt(DIMOStockPrtsreturnDtm.getValueAt(i, 0).toString());
                        try {
                            int paids= DIMOPartsReturnController.changeDIMOPartStatus(1, retID);
                           // JOptionPane.showMessageDialog(this, "successfully.", "Succeeded", JOptionPane.INFORMATION_MESSAGE);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(DealerReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(DealerReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                }
                JOptionPane.showMessageDialog(this, "Dimo Return Accepetd successfully.", "Succeeded", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAcceptedActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        for(int i=0;i<DIMOStockPrtsreturnDtm.getRowCount();i++) {
                    if(Boolean.parseBoolean(DIMOStockPrtsreturnDtm.getValueAt(i, 9)+"")== true){
                    int retID = Integer.parseInt(DIMOStockPrtsreturnDtm.getValueAt(i, 0).toString());
                    
                    int StockID = Integer.parseInt(DIMOStockPrtsreturnDtm.getValueAt(i, 2).toString());
                     int ItemID = Integer.parseInt(DIMOStockPrtsreturnDtm.getValueAt(i, 1).toString());
                     int retQty = Integer.parseInt(DIMOStockPrtsreturnDtm.getValueAt(i, 4).toString());
                        try {
                            int paids= DIMOPartsReturnController.changeDIMOPartStatus(1, retID);
                            int a=DIMOPartsReturnController.updateStockDetailQuantityDIMOPart(retQty, ItemID, StockID);
                                    
                            
                            
                           // JOptionPane.showMessageDialog(this, " Reject successfully.", "Succeeded", JOptionPane.INFORMATION_MESSAGE);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(DealerReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(DealerReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                }
                JOptionPane.showMessageDialog(this, "Dimo Return Reject successfully.", "Succeeded", JOptionPane.INFORMATION_MESSAGE);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccepted;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblAllReturns;
    private javax.swing.JTable tblDIMOStockPartReturn;
    private javax.swing.JTable tblOtherSupplierReturns;
    // End of variables declaration//GEN-END:variables
}
