/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views.purchaseorderviws;

import controllers.ItemController;
import controllers.SearchCategoryController;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import utilities_new.Combosearch;

/**
 *
 * @author SHdinesh Madushanka
 */
public class PurchaseOrderParts extends javax.swing.JDialog {

    private DefaultTableModel tblSelectItemDtm, tblSelectedDtm;
    private Combosearch keySearch;

    /**
     * Creates new form PurchaseOrderParts
     */
    public PurchaseOrderParts(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public PurchaseOrderParts(java.awt.Frame parent, boolean modal, DefaultTableModel dtm) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        tblSelectItemDtm = (DefaultTableModel) tblSelectItem.getModel();
        tblSelectedDtm = dtm;
        try {
            loadAllTataPartsToSelect(tblSelectItemDtm);
            SearchCategoryController.fillSearchKeys(cmbSearchKeys);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        keySearch = new Combosearch();
        keySearch.setSearchableCombo(cmbSearchKeys, true, "Search Key is not registered");
    }

    public void loadAllTataPartsToSelect(DefaultTableModel allPartsDtm) throws ClassNotFoundException, SQLException {
        ResultSet data = ItemController.getAllTataPartsForPurchase();
        String tableRow[] = new String[10];
        int rowCount = allPartsDtm.getRowCount();
        if (rowCount >= 0) {
            allPartsDtm.setRowCount(0);
        }

        while (data.next()) {
            for (int i = 0; i < 10; i++) {
                if (i == 9) {
                    tableRow[i] = "All";
                } else {
                    tableRow[i] = data.getString(i + 1);
                }

            }
            allPartsDtm.addRow(tableRow);
        }
    }

    /*new*/
    public void addNewItemsToTable() throws ClassNotFoundException, SQLException {
        DecimalFormat df = new DecimalFormat("#.00");
        df.setMaximumFractionDigits(2);
        int selectedRow = tblSelectItem.getSelectedRow();
        String partNo = tblSelectItem.getValueAt(selectedRow, 1).toString();
        String description = tblSelectItem.getValueAt(selectedRow, 2).toString();
        int itemCode = Integer.parseInt(tblSelectItem.getValueAt(selectedRow, 0).toString());
        double buyingPrice = Double.parseDouble(tblSelectItem.getValueAt(selectedRow, 3).toString());
        double formattedBuyingPrice = Double.parseDouble(df.format(buyingPrice));
        int quantity = Integer.parseInt(txtQty.getText().trim());

        double amount = Double.parseDouble(df.format(buyingPrice * quantity));

        if (partNo == null || partNo == "") {
            JOptionPane.showMessageDialog(this, "Please select an item to add", "Error in items", JOptionPane.WARNING_MESSAGE);
        } else if (quantity == 0 || txtQty.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Quantity cannot be empty or 0", "Error in quantity", JOptionPane.WARNING_MESSAGE);
        } else {
            Object obj[] = {itemCode, partNo, description, formattedBuyingPrice, quantity, amount};
            tblSelectedDtm.addRow(obj);
            //clearFields();
            //mainPanel.checkButtons();
            //mainPanel.checkBillButton();
            // mainPanel.calculate();
            dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbSearchKeys = new javax.swing.JComboBox();
        txtPartSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSelectItem = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        txtQty = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All TATA Parts");
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        cmbSearchKeys.setEditable(true);
        cmbSearchKeys.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbSearchKeysPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbSearchKeys.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbSearchKeysKeyReleased(evt);
            }
        });

        txtPartSearch.setText("Search...");
        txtPartSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartSearchActionPerformed(evt);
            }
        });
        txtPartSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPartSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPartSearchFocusLost(evt);
            }
        });
        txtPartSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPartSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbSearchKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPartSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSearchKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPartSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblSelectItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        tblSelectItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblSelectItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "part id", "Part No.", "Description", "Buying Price", "Category", "Model", "Re Order Qty", "Last Stock Date", "Remaining Qty.", "All"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSelectItem.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblSelectItem.setRowHeight(20);
        tblSelectItem.setRowMargin(2);
        tblSelectItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSelectItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSelectItemKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblSelectItem);
        if (tblSelectItem.getColumnModel().getColumnCount() > 0) {
            tblSelectItem.getColumnModel().getColumn(0).setMinWidth(0);
            tblSelectItem.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblSelectItem.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSelectItem.getColumnModel().getColumn(1).setMinWidth(110);
            tblSelectItem.getColumnModel().getColumn(1).setPreferredWidth(110);
            tblSelectItem.getColumnModel().getColumn(1).setMaxWidth(110);
            tblSelectItem.getColumnModel().getColumn(2).setMinWidth(180);
            tblSelectItem.getColumnModel().getColumn(2).setPreferredWidth(180);
            tblSelectItem.getColumnModel().getColumn(2).setMaxWidth(180);
            tblSelectItem.getColumnModel().getColumn(4).setMinWidth(100);
            tblSelectItem.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblSelectItem.getColumnModel().getColumn(4).setMaxWidth(100);
            tblSelectItem.getColumnModel().getColumn(8).setMinWidth(150);
            tblSelectItem.getColumnModel().getColumn(8).setPreferredWidth(150);
            tblSelectItem.getColumnModel().getColumn(8).setMaxWidth(150);
            tblSelectItem.getColumnModel().getColumn(9).setMinWidth(0);
            tblSelectItem.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblSelectItem.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtQty.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtQty.setText("0");
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtyFocusGained(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });

        lblQty.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblQty.setText("Quantity :");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(608, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSearchKeysPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbSearchKeysPopupMenuWillBecomeInvisible
        String selectedItem = cmbSearchKeys.getSelectedItem().toString();

        try {

            final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblSelectItemDtm);
            tblSelectItem.setRowSorter(sorter);
            sorter.setRowFilter(RowFilter.regexFilter(("(?i)" + selectedItem)));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbSearchKeysPopupMenuWillBecomeInvisible

    private void cmbSearchKeysKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSearchKeysKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchKeysKeyReleased

    private void txtPartSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartSearchActionPerformed

    private void txtPartSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPartSearchFocusGained
        txtPartSearch.setText("");
    }//GEN-LAST:event_txtPartSearchFocusGained

    private void txtPartSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPartSearchFocusLost
        txtPartSearch.setText("Search...");
    }//GEN-LAST:event_txtPartSearchFocusLost

    private void txtPartSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPartSearchKeyReleased
        try {
            final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblSelectItemDtm);
            tblSelectItem.setRowSorter(sorter);
            sorter.setRowFilter(RowFilter.regexFilter(("(?i)" + txtPartSearch.getText())));
            int keyCode = evt.getKeyCode();

            if (keyCode == KeyEvent.VK_DOWN) {
                tblSelectItem.requestFocus();
                tblSelectItem.changeSelection(0, 0, false, false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtPartSearchKeyReleased

    private void tblSelectItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSelectItemKeyReleased
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ENTER) {
            tblSelectItem.requestFocus(false);
            tblSelectItem.changeSelection(tblSelectItem.getSelectedRow() - 1, 0, false, false);
            txtQty.requestFocus();
        }
    }//GEN-LAST:event_tblSelectItemKeyReleased

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        btnAdd.doClick();
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusGained
        txtQty.selectAll();
    }//GEN-LAST:event_txtQtyFocusGained

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
//        ValidateValues.validateTextFieldForNumber(txtQty);
//        if (evt.getKeyCode() == evt.VK_ENTER) {
//            btnAddToTable.requestFocus();
//        }
    }//GEN-LAST:event_txtQtyKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            addNewItemsToTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (NumberFormatException nfe) {
            nfe.printStackTrace();
            JOptionPane.showMessageDialog(this, "Please enter values again correctly", "Error in values", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "Please enter values again correctly", "Error in values", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrderParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrderParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrderParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrderParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PurchaseOrderParts dialog = new PurchaseOrderParts(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox cmbSearchKeys;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTable tblSelectItem;
    private javax.swing.JTextField txtPartSearch;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
