/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.employee;

import controllers.EmployeeController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import utilities_new.ValidateValues;

/**
 *
 * @author Iresha Lakmali
 */
public class AddEmployee extends javax.swing.JDialog {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        txt_employee_name.requestFocus();
    }

    public void addNewEmployee() {
        try {

            String employee_name = txt_employee_name.getText();
            String employee_code = txt_employee_code.getText();
            String employee_contact_no_1 = txt_contact_no_1.getText();
            String employee_contact_no_2 = txt_contact_no_2.getText();
            String address = txt_employee_address.getText();
            Date d1 = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String added_date = sdf.format(d1);
            sdf.applyLocalizedPattern("HH:mm:ss");
            String addedTime = sdf.format(d1);
            int status = 1;
            int value = 0;
            if (employee_name == "" || employee_name == null || employee_name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter Employee name", "No employee name", JOptionPane.ERROR_MESSAGE);
            } else {
                models.Employee employee = new models.Employee(value, employee_name, employee_code, employee_contact_no_1, employee_contact_no_2, employee_code, added_date, addedTime, status);
                //  Service service = new Service(service_code, service_name, service_cost, remarks, added_date, addedTime,service_charge, status);
                // value = ServiceController.addNewService(service);
                value = EmployeeController.addNewEmployee(employee);

            }

            if (value > 0) {
                JOptionPane.showMessageDialog(this, "New Employee Successfully Added", "Successful", JOptionPane.INFORMATION_MESSAGE);
                refreshFields();
                dispose();
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            // JOptionPane.showMessageDialog(this, "Check your entered values again..", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void refreshFields() {
        txt_employee_name.setText("");
        txt_employee_code.setText("");
        txt_contact_no_1.setText("");
        txt_contact_no_2.setText("");
        txt_employee_address.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_employee_name = new javax.swing.JTextField();
        txt_employee_code = new javax.swing.JTextField();
        txt_contact_no_1 = new javax.swing.JTextField();
        txt_contact_no_2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_employee_address = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Employee");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Employee Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Employee Code :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Address :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Contact No 1 :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Contact No 2 :");

        txt_employee_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_employee_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employee_nameActionPerformed(evt);
            }
        });

        txt_employee_code.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_employee_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employee_codeActionPerformed(evt);
            }
        });

        txt_contact_no_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_contact_no_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contact_no_1ActionPerformed(evt);
            }
        });
        txt_contact_no_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_contact_no_1KeyReleased(evt);
            }
        });

        txt_contact_no_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_contact_no_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contact_no_2ActionPerformed(evt);
            }
        });
        txt_contact_no_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_contact_no_2KeyReleased(evt);
            }
        });

        txt_employee_address.setColumns(20);
        txt_employee_address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_employee_address.setRows(5);
        txt_employee_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_employee_addressKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txt_employee_address);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_employee_code)
                    .addComponent(txt_contact_no_1)
                    .addComponent(txt_contact_no_2)
                    .addComponent(txt_employee_name, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_contact_no_1, txt_contact_no_2, txt_employee_code, txt_employee_name});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_employee_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_employee_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_contact_no_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_contact_no_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_contact_no_1, txt_contact_no_2, txt_employee_code, txt_employee_name});

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_employee_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employee_codeActionPerformed
        txt_contact_no_1.requestFocus();
    }//GEN-LAST:event_txt_employee_codeActionPerformed

    private void txt_contact_no_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contact_no_1ActionPerformed
        txt_contact_no_2.requestFocus();
    }//GEN-LAST:event_txt_contact_no_1ActionPerformed

    private void txt_employee_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employee_nameActionPerformed
        txt_employee_code.requestFocus();
    }//GEN-LAST:event_txt_employee_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_contact_no_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contact_no_2ActionPerformed
        txt_employee_address.requestFocus();
    }//GEN-LAST:event_txt_contact_no_2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        addNewEmployee();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_contact_no_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contact_no_1KeyReleased
        ValidateValues.validateTextFieldForContactNumber(txt_contact_no_1);
    }//GEN-LAST:event_txt_contact_no_1KeyReleased

    private void txt_contact_no_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contact_no_2KeyReleased
        ValidateValues.validateTextFieldForContactNumber(txt_contact_no_2);
    }//GEN-LAST:event_txt_contact_no_2KeyReleased

    private void txt_employee_addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_employee_addressKeyPressed
//jButton2.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employee_addressKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEmployee dialog = new AddEmployee(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_contact_no_1;
    private javax.swing.JTextField txt_contact_no_2;
    private javax.swing.JTextArea txt_employee_address;
    private javax.swing.JTextField txt_employee_code;
    private javax.swing.JTextField txt_employee_name;
    // End of variables declaration//GEN-END:variables
}
