/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.employee;

import controllers.EmployeeController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author insaf
 */
public class Employee extends javax.swing.JPanel {

    private DefaultTableModel employee_dtm;

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        checkEmpButtons();
        employee_dtm = (DefaultTableModel) tbl_employee.getModel();

        try {
            EmployeeController.loadAllEmployee(employee_dtm);
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }

    }

    public void checkEmpButtons() {
        int rowCount = tbl_employee.getSelectedRowCount();
        if ((rowCount > 0)) {
            btnUpdateEmployee.setEnabled(true);
            btnDeleteEmployee.setEnabled(true);
        } else {
            btnUpdateEmployee.setEnabled(false);
            btnDeleteEmployee.setEnabled(false);
        }
    }

    public void deleteEmployee() {
        int[] selectedRows = tbl_employee.getSelectedRows();

        try {
            while (selectedRows.length > 0) {
                int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this employee?", "Delete", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                int value = 0;
                if (option == 0) {
                    models.Employee employee = new models.Employee();
                    employee.setEmployeeId(Integer.parseInt((String) tbl_employee.getValueAt(selectedRows[0], 0)));
                    int deleteEmployee = EmployeeController.deleteEmployee(employee);
                    employee_dtm.removeRow(selectedRows[0]);
                    selectedRows = tbl_employee.getSelectedRows();

                    if (deleteEmployee > 0) {
                        JOptionPane.showMessageDialog(this, "Employee successfully deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
                        //  checkServiceButtons();
                    }
                } else {
                    tbl_employee.clearSelection();
                    //   checkServiceButtons();
                    break;

                }

            }
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (SQLException sQLException) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_employee = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtEmployeeSearch = new javax.swing.JTextField();
        btnNewEmployee = new javax.swing.JButton();
        btnUpdateEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();

        tbl_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee_Id", "Name", "Code", "Contact No 1", "Contact No 2", "Address", "Date Registerd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_employeeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_employeeMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_employee);
        if (tbl_employee.getColumnModel().getColumnCount() > 0) {
            tbl_employee.getColumnModel().getColumn(0).setMinWidth(0);
            tbl_employee.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbl_employee.getColumnModel().getColumn(0).setMaxWidth(0);
            tbl_employee.getColumnModel().getColumn(6).setMinWidth(0);
            tbl_employee.getColumnModel().getColumn(6).setPreferredWidth(0);
            tbl_employee.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        jLabel1.setText("Search :");

        txtEmployeeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeSearchActionPerformed(evt);
            }
        });
        txtEmployeeSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeSearchKeyReleased(evt);
            }
        });

        btnNewEmployee.setText("New");
        btnNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEmployeeActionPerformed(evt);
            }
        });

        btnUpdateEmployee.setText("Update");
        btnUpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmployeeActionPerformed(evt);
            }
        });

        btnDeleteEmployee.setText("Delete");
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(txtEmployeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteEmployee, btnNewEmployee, btnUpdateEmployee});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmployeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewEmployee)
                    .addComponent(btnUpdateEmployee)
                    .addComponent(btnDeleteEmployee))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDeleteEmployee, btnNewEmployee, btnUpdateEmployee});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeSearchActionPerformed

    private void btnNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEmployeeActionPerformed
        try {
            AddEmployee addEmployee = new AddEmployee(null, true);
            addEmployee.setVisible(true);
            EmployeeController.loadAllEmployee(employee_dtm);
            checkEmpButtons();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnNewEmployeeActionPerformed

    private void btnUpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmployeeActionPerformed
        int row = tbl_employee.getSelectedRow();
        int supplierID = Integer.parseInt(tbl_employee.getValueAt(row, 0).toString());

        int val0 = Integer.parseInt(tbl_employee.getValueAt(row, 0).toString());
        String val1 = tbl_employee.getValueAt(row, 1).toString();
        String val2 = tbl_employee.getValueAt(row, 2).toString();
        String val3 = tbl_employee.getValueAt(row, 3).toString();
        String val4 = tbl_employee.getValueAt(row, 4).toString();
        String val5 = tbl_employee.getValueAt(row, 5).toString();
        //    String val6 = tbl_employee.getValueAt(row, 6).toString();
        models.Employee employee = new models.Employee();

        employee.setEmployeeId(val0);
        employee.setEmployeeCode(val2);
        employee.setEmployeeName(val1);
        employee.setEmployeeContactNo1(val3);
        employee.setEmployeeContactNo2(val4);
        employee.setEmployeeAddress(val5);
        UpdateEmployee updateEmployee = new UpdateEmployee(null, true);
        updateEmployee.setUpdateEmployee(employee);
        updateEmployee.setVisible(true);
        try {
            EmployeeController.loadAllEmployee(employee_dtm);
            checkEmpButtons();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }

    }//GEN-LAST:event_btnUpdateEmployeeActionPerformed

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeActionPerformed
        deleteEmployee();
    }//GEN-LAST:event_btnDeleteEmployeeActionPerformed

    private void txtEmployeeSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeSearchKeyReleased
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(employee_dtm);
        tbl_employee.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtEmployeeSearch.getText()));
    }//GEN-LAST:event_txtEmployeeSearchKeyReleased

    private void tbl_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_employeeMouseClicked
        int empID = Integer.parseInt(tbl_employee.getValueAt(tbl_employee.getSelectedRow(), 0).toString());
        if (empID != 1) {
            checkEmpButtons();
        } else {
            btnUpdateEmployee.setEnabled(false);
            btnDeleteEmployee.setEnabled(false);
        }

    }//GEN-LAST:event_tbl_employeeMouseClicked

    private void tbl_employeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_employeeMousePressed
        int empID = Integer.parseInt(tbl_employee.getValueAt(tbl_employee.getSelectedRow(), 0).toString());
        if (empID != 1) {
            checkEmpButtons();
        } else {
            btnUpdateEmployee.setEnabled(false);
            btnDeleteEmployee.setEnabled(false);
        }
    }//GEN-LAST:event_tbl_employeeMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnNewEmployee;
    private javax.swing.JButton btnUpdateEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_employee;
    private javax.swing.JTextField txtEmployeeSearch;
    // End of variables declaration//GEN-END:variables
}
