/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.employee;

import controllers.EmployeeController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import utilities_new.ValidateValues;

/**
 *
 * @author insaf
 */
public class UpdateEmployee extends javax.swing.JDialog {

    private int employeeId;

    /**
     * Creates new form UpdateEmployee
     */
    public UpdateEmployee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        txt_u_employee_name.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_u_employee_name = new javax.swing.JTextField();
        txt_u_employee_code = new javax.swing.JTextField();
        txt_u_contact_no_1 = new javax.swing.JTextField();
        txt_u_contact_no_2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_u_address = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Employee");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Employee Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Employee Code :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Contact No 1 :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Contact No 2 :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Address :");

        txt_u_employee_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_u_employee_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_u_employee_nameActionPerformed(evt);
            }
        });

        txt_u_employee_code.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_u_employee_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_u_employee_codeActionPerformed(evt);
            }
        });

        txt_u_contact_no_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_u_contact_no_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_u_contact_no_1ActionPerformed(evt);
            }
        });
        txt_u_contact_no_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_u_contact_no_1KeyReleased(evt);
            }
        });

        txt_u_contact_no_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_u_contact_no_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_u_contact_no_2ActionPerformed(evt);
            }
        });
        txt_u_contact_no_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_u_contact_no_2KeyReleased(evt);
            }
        });

        txt_u_address.setColumns(20);
        txt_u_address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_u_address.setRows(5);
        txt_u_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_u_addressKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txt_u_address);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_u_contact_no_2)
                    .addComponent(txt_u_contact_no_1)
                    .addComponent(txt_u_employee_code)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_u_employee_name, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, txt_u_contact_no_1, txt_u_contact_no_2, txt_u_employee_code, txt_u_employee_name});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_u_employee_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_u_employee_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_u_contact_no_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_u_contact_no_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_u_contact_no_1, txt_u_contact_no_2, txt_u_employee_code, txt_u_employee_name});

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_u_contact_no_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_u_contact_no_1ActionPerformed
      txt_u_contact_no_2.requestFocus();   // TODO add your handling code here:
    }//GEN-LAST:event_txt_u_contact_no_1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_u_employee_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_u_employee_codeActionPerformed
txt_u_contact_no_1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_u_employee_codeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        models.Employee employee = new models.Employee();
        String employee_name = txt_u_employee_name.getText();
        if (employee_name == "" || employee_name == null || employee_name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Employee name", "No employee name", JOptionPane.ERROR_MESSAGE);
        } else {
            employee.setEmployeeId(employeeId);
            employee.setEmployeeName(employee_name);
            employee.setEmployeeCode(txt_u_employee_code.getText());
            employee.setEmployeeContactNo1(txt_u_contact_no_1.getText());
            employee.setEmployeeContactNo2(txt_u_contact_no_2.getText());
            employee.setEmployeeAddress(txt_u_address.getText());
        }
        try {
            int updateEmployee = EmployeeController.updateEmployee(employee);
            if (updateEmployee > 0) {
                JOptionPane.showMessageDialog(this, "Employee successfully updated", "Success", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }

        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_u_contact_no_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_u_contact_no_1KeyReleased
        ValidateValues.validateTextFieldForContactNumber(txt_u_contact_no_1);

    }//GEN-LAST:event_txt_u_contact_no_1KeyReleased

    private void txt_u_contact_no_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_u_contact_no_2KeyReleased
        ValidateValues.validateTextFieldForContactNumber(txt_u_contact_no_2);
    }//GEN-LAST:event_txt_u_contact_no_2KeyReleased

    private void txt_u_employee_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_u_employee_nameActionPerformed
txt_u_employee_code.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_u_employee_nameActionPerformed

    private void txt_u_contact_no_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_u_contact_no_2ActionPerformed
txt_u_address.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_u_contact_no_2ActionPerformed

    private void txt_u_addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_u_addressKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_txt_u_addressKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateEmployee dialog = new UpdateEmployee(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_u_address;
    private javax.swing.JTextField txt_u_contact_no_1;
    private javax.swing.JTextField txt_u_contact_no_2;
    private javax.swing.JTextField txt_u_employee_code;
    private javax.swing.JTextField txt_u_employee_name;
    // End of variables declaration//GEN-END:variables

    public void setUpdateEmployee(models.Employee employee) {
        employeeId = employee.getEmployeeId();
        txt_u_employee_code.setText(employee.getEmployeeCode());
        txt_u_employee_name.setText(employee.getEmployeeName());

        txt_u_contact_no_1.setText(employee.getEmployeeContactNo1());
        txt_u_contact_no_2.setText(employee.getEmployeeContactNo2());
        txt_u_address.setText(employee.getEmployeeAddress());

    }

}
