/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OtherSupplierReturns.java
 *
 * Created on May 7, 2015, 8:25:38 AM
 */
package views.stockviws;

import controllers.OtherSupplierReturnController;
import controllers.StockController;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import models.OtherSupplierReturn;
import models.OtherSupplierReturnDetail;

/**
 *
 * @author HP2000
 */
public class OtherSupplierReturns extends javax.swing.JDialog {
    
 private DefaultTableModel otherRetTableModel;
    private int stockID,itemID;
    /** Creates new form OtherSupplierReturns */
    public OtherSupplierReturns(java.awt.Frame parent, boolean modal,int stockID) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        otherRetTableModel = (DefaultTableModel) tblOtherSupplierReturn.getModel();
        //this.stockID = stockID;
       // this.itemID=itemID;
        try {
            StockController.loadAllOtherStockDetails(stockID, otherRetTableModel);
         // CustomerReturnsController.loadAllOrderDataToReturn(stockID, otherRetTableModel);

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
        }
    }

    public void addNewOtherReturn() throws ClassNotFoundException, SQLException {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String returnDate = sdf.format(new Date());
        sdf.applyPattern("HH:mm:ss");
        String returnTime = sdf.format(new Date());
        double returnAmount = Double.parseDouble(txtOtherRet.getText());
        int other_returnStatus = 0;
        int status = 1;
        
        OtherSupplierReturn sr = new OtherSupplierReturn();
       // cr.setRetNumber(returnNo);
        sr.setReturnAmount(returnAmount);
        sr.setReturnDate(returnDate);
        sr.setReturnTime(returnTime);
       sr.setStatus(status);
       sr.setOtherReturnStatus(other_returnStatus);
       
        int rowCount = tblOtherSupplierReturn.getRowCount();
        ArrayList<OtherSupplierReturnDetail> crDetailList = new ArrayList<>();
       for (int i = 0; i < rowCount; i++) {
            Object isReturnO = tblOtherSupplierReturn.getValueAt(i, 7);
            boolean isReturn = Boolean.parseBoolean((isReturnO != null && !isReturnO.toString().isEmpty() ? isReturnO.toString() : "0"));
            if (isReturn) {
                int StockID = Integer.parseInt(tblOtherSupplierReturn.getValueAt(i, 0).toString());
                int ItemID = Integer.parseInt(tblOtherSupplierReturn.getValueAt(i, 1).toString());
                int returnQuantity = Integer.parseInt(tblOtherSupplierReturn.getValueAt(i, 6).toString());
                int Quantity = Integer.parseInt(tblOtherSupplierReturn.getValueAt(i, 4).toString());
                int actualqty=0;
                actualqty=Quantity-returnQuantity;
              
                double buyingPrice = Double.parseDouble(tblOtherSupplierReturn.getValueAt(i, 5).toString());
                int status2=1;
               
               // OtherSupplierReturnDetail crDetail = new OtherSupplierReturnDetail(StockID, ItemID,returnQuantity,buyingPrice,status);
               OtherSupplierReturnDetail crDetail = new OtherSupplierReturnDetail(StockID, ItemID, buyingPrice, returnQuantity, status); 
                crDetailList.add(crDetail);
                
            OtherSupplierReturnDetail stockupdate = new OtherSupplierReturnDetail(StockID,  ItemID, actualqty);

            OtherSupplierReturnController.updateStock(stockupdate);
            }
        }
        boolean isAdded = OtherSupplierReturnController.addNewOtherSupplierReturn(sr, crDetailList);
        if (isAdded) {
            
           // OtherSupplierReturn.updateDebtsOnReturn(StockID, Double.parseDouble(String.format("%.2f", totalReturnAmount)));
            JOptionPane.showMessageDialog(this, "Returns added successfully.", "Succeeded", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "An error occured while adding returns", "Error", JOptionPane.INFORMATION_MESSAGE);

        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOtherSupplierReturn = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtOtherRet = new javax.swing.JTextField();
        btnOtherSupRet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Other Supplier Returns");

        tblOtherSupplierReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "stock id", "itemID", "Part No.", "Description", " Quantity", "Buying Price(Rs.)", "Return Qty.", "Return"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOtherSupplierReturn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblOtherSupplierReturnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblOtherSupplierReturnKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblOtherSupplierReturn);
        if (tblOtherSupplierReturn.getColumnModel().getColumnCount() > 0) {
            tblOtherSupplierReturn.getColumnModel().getColumn(0).setMinWidth(0);
            tblOtherSupplierReturn.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblOtherSupplierReturn.getColumnModel().getColumn(0).setMaxWidth(0);
            tblOtherSupplierReturn.getColumnModel().getColumn(1).setMinWidth(0);
            tblOtherSupplierReturn.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblOtherSupplierReturn.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        jLabel1.setText("Other Supplier Return Amount :");

        txtOtherRet.setEditable(false);
        txtOtherRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtherRetActionPerformed(evt);
            }
        });

        btnOtherSupRet.setText("Add to Other Supplier Returns");
        btnOtherSupRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtherSupRetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(txtOtherRet, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btnOtherSupRet)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOtherRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOtherSupRet))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOtherRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtherRetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtherRetActionPerformed

    private void tblOtherSupplierReturnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblOtherSupplierReturnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblOtherSupplierReturnKeyPressed

    private void tblOtherSupplierReturnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblOtherSupplierReturnKeyReleased
       int rowCount = tblOtherSupplierReturn.getRowCount();

        double totalReturnAmount = 0;
        for (int i = 0; i < rowCount; i++) {
            //getdata values in column...
            Object object = tblOtherSupplierReturn.getValueAt(i, 7);
//            String value = object.toString();            
//            boolean isReturn = Boolean.parseBoolean(value);
            if (object != null) {
                String ret = tblOtherSupplierReturn.getValueAt(i, 6).toString();
                double retQty = Double.parseDouble((ret != null && !ret.isEmpty() ? ret : "0"));
                
                String inv =tblOtherSupplierReturn.getValueAt(i, 4).toString();
                double invQty = Double.parseDouble((inv !=null && !inv.isEmpty() ? inv : "0"));
                
                String invA = tblOtherSupplierReturn.getValueAt(i, 5).toString();
                double invAmount = Double.parseDouble((invA !=null && !invA.isEmpty() ? invA : "0"));

                totalReturnAmount += invAmount * retQty;
                System.out.println(totalReturnAmount);
            }
        }
        txtOtherRet.setText(String.format("%.2f", totalReturnAmount));           // TODO add your handling code here:
    }//GEN-LAST:event_tblOtherSupplierReturnKeyReleased

    private void btnOtherSupRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtherSupRetActionPerformed

         try {
            addNewOtherReturn();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtherSupRetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                OtherSupplierReturns dialog = new OtherSupplierReturns(new javax.swing.JFrame(), true,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtherSupRet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOtherSupplierReturn;
    private javax.swing.JTextField txtOtherRet;
    // End of variables declaration//GEN-END:variables
}
