/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.debtviews;

import controllers.DebtController;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class DebtDetailsPain extends javax.swing.JPanel {

    private DefaultTableModel pendingDebtsDtm, debtDetailsDtm;

    /**
     * Creates new form DebtDetailsPain
     */
    public DebtDetailsPain() {
        initComponents();
        pendingDebtsDtm = (DefaultTableModel) tblPendingDebts.getModel();
        debtDetailsDtm = (DefaultTableModel) tblDebtDetails.getModel();
//        try {
//            DebtController.loadAllPendingDebts(pendingDebtsDtm);
//            checkEndDateButton();
//        checkPaymentDetailButton();
//        } catch (ClassNotFoundException ex) {
//        } catch (SQLException ex) {
//        }

    }

    public void checkEndDateButton() {
        int selectedRows = tblPendingDebts.getSelectedRowCount();
        if (selectedRows > 0) {
            btnManageEndDate.setEnabled(true);
            btnAddPayment.setEnabled(true);
        } else {
            btnManageEndDate.setEnabled(false);
            btnAddPayment.setEnabled(false);
        }
    }

    public void checkPaymentDetailButton() {
        int selectedRows = tblDebtDetails.getSelectedRowCount();
        if (selectedRows > 0) {
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
        } else {
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendingDebts = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDebtDetails = new javax.swing.JTable();
        btnManageEndDate = new javax.swing.JButton();
        btnAddPayment = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        tblPendingDebts.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblPendingDebts.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tblPendingDebts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debt ID", "Sales Order No", "Debt Date", "End Date", "Debt Amount", "Pending Amount", "Garage Commission"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPendingDebts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPendingDebtsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPendingDebtsMousePressed(evt);
            }
        });
        tblPendingDebts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblPendingDebtsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPendingDebts);
        if (tblPendingDebts.getColumnModel().getColumnCount() > 0) {
            tblPendingDebts.getColumnModel().getColumn(0).setMinWidth(0);
            tblPendingDebts.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblPendingDebts.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        txtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jButton1.setText("Search");

        tblDebtDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblDebtDetails.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tblDebtDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DetailID", "Payment Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDebtDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDebtDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDebtDetails);
        if (tblDebtDetails.getColumnModel().getColumnCount() > 0) {
            tblDebtDetails.getColumnModel().getColumn(0).setMinWidth(0);
            tblDebtDetails.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblDebtDetails.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnManageEndDate.setText("Manage End Date");
        btnManageEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEndDateActionPerformed(evt);
            }
        });

        btnAddPayment.setText("Add Payment");
        btnAddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPaymentActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Payment");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Payment");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(btnManageEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddPayment)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddPayment, btnDelete, btnUpdate});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPayment)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddPayment, btnDelete, btnUpdate});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, txtSearch});

        jTabbedPane1.addTab("Pending", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblPendingDebtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPendingDebtsMouseClicked
        checkEndDateButton();
        int selectedRow = tblPendingDebts.getSelectedRow();
        int debtID = Integer.parseInt(tblPendingDebts.getValueAt(selectedRow, 0).toString());
        try {
            DebtController.loadAllDebtDetails(debtDetailsDtm, debtID);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_tblPendingDebtsMouseClicked

    private void tblPendingDebtsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPendingDebtsMousePressed
        checkEndDateButton();
        int selectedRow = tblPendingDebts.getSelectedRow();
        int debtID = Integer.parseInt(tblPendingDebts.getValueAt(selectedRow, 0).toString());
        try {
            DebtController.loadAllDebtDetails(debtDetailsDtm, debtID);
        } catch (SQLException ex) {
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_tblPendingDebtsMousePressed

    private void tblPendingDebtsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPendingDebtsKeyReleased
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_DOWN || keyCode == KeyEvent.VK_UP) {
            int selectedRow = tblPendingDebts.getSelectedRow();
            int debtID = Integer.parseInt(tblPendingDebts.getValueAt(selectedRow, 0).toString());
            try {
                DebtController.loadAllDebtDetails(debtDetailsDtm, debtID);
            } catch (SQLException ex) {
            } catch (ClassNotFoundException ex) {
            }
        }
    }//GEN-LAST:event_tblPendingDebtsKeyReleased

    private void btnManageEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEndDateActionPerformed

        int selectedRow = tblPendingDebts.getSelectedRow();
        int orderID = Integer.parseInt(tblPendingDebts.getValueAt(selectedRow, 0).toString());
        new ChangeEndDate(null, true, orderID, pendingDebtsDtm).setVisible(true);


    }//GEN-LAST:event_btnManageEndDateActionPerformed

    private void tblDebtDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDebtDetailsMouseClicked
        checkPaymentDetailButton();
    }//GEN-LAST:event_tblDebtDetailsMouseClicked

    private void btnAddPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPaymentActionPerformed
        int debtID = Integer.parseInt(tblPendingDebts.getValueAt(tblPendingDebts.getSelectedRow(), 0).toString());
        // double pendingAmount = 
        //new NewPayment(null, true, debtID, pendingDebtsDtm).setVisible(true);

    }//GEN-LAST:event_btnAddPaymentActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPayment;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnManageEndDate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDebtDetails;
    private javax.swing.JTable tblPendingDebts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
