/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SupplierPayment.java
 *
 * Created on May 22, 2015, 3:19:23 PM
 */
package views.debtviews;


import controllers.PaymentSupplierController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.PaymentSupplier;

/**
 *
 * @author HP2000
 */
public class SupplierPayment extends javax.swing.JDialog {
     private DefaultTableModel servicedtm;
    
    /** Creates new form SupplierPayment */
    public SupplierPayment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setTitle("New Supplier Payment");
        setLocationRelativeTo(null);
        jDateSuppPayDate.setDate(new Date());
    }
     public void addNewPaymentToSupplier() {
        try {
            String invoicenumber = txtSuppPayInvNum.getText();
            String supplier = txtSuppPaySupplier.getText();
            String remarks = txtSuppPayRemarks.getText();
            double amount = Double.parseDouble(txtSuppPayAmount.getText());
            Date d1 = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           // String date = sdf.format(d1);
            String date = sdf.format(jDateSuppPayDate.getDate());
            sdf.applyPattern("HH:mm:ss");
            String time = sdf.format(d1);

            if ("".equals(invoicenumber) || invoicenumber == null || invoicenumber.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter invoice number.", "No Invoice Number", JOptionPane.ERROR_MESSAGE);
            }
            else if ("".equals(supplier) || supplier == null || supplier.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter supplier name.", "No supplier name", JOptionPane.ERROR_MESSAGE);
             } 
            else if ("".equals(remarks) || remarks == null || remarks.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter remarks.", "No Remarks", JOptionPane.ERROR_MESSAGE);
            
            }
            else if (amount == 0) {
                JOptionPane.showMessageDialog(this, "Amount cannot be 0 or minus", "Wrong Amount", JOptionPane.ERROR_MESSAGE);
            }
            else {
               PaymentSupplier payment = new PaymentSupplier( invoicenumber, supplier, date, time, amount, remarks, 1);
                                                                
                      int value = PaymentSupplierController.addSupplierPayment(payment);
                if (value > 0) {
                    JOptionPane.showMessageDialog(this, "Payment to supplier added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please check your values again.", "Error in values", JOptionPane.ERROR_MESSAGE);
            //ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateSuppPayDate = new com.toedter.calendar.JDateChooser();
        txtSuppPayInvNum = new javax.swing.JTextField();
        txtSuppPaySupplier = new javax.swing.JTextField();
        txtSuppPayAmount = new javax.swing.JTextField();
        txtSuppPayRemarks = new javax.swing.JTextField();
        btnSuppPayAdd = new javax.swing.JButton();
        btnSuppPayCansel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Supplier Payment");

        jLabel1.setText("Invoice Number");

        jLabel2.setText("Supplier");

        jLabel3.setText("Date");

        jLabel4.setText("Amount");

        jLabel5.setText("Remarks");

        jDateSuppPayDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateSuppPayDateKeyPressed(evt);
            }
        });

        txtSuppPayInvNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuppPayInvNumActionPerformed(evt);
            }
        });

        txtSuppPaySupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuppPaySupplierActionPerformed(evt);
            }
        });

        txtSuppPayAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuppPayAmountActionPerformed(evt);
            }
        });

        txtSuppPayRemarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuppPayRemarksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSuppPayRemarks)
                    .addComponent(txtSuppPayAmount)
                    .addComponent(txtSuppPaySupplier)
                    .addComponent(txtSuppPayInvNum)
                    .addComponent(jDateSuppPayDate, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateSuppPayDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSuppPayInvNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSuppPaySupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSuppPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSuppPayRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnSuppPayAdd.setText("Add");
        btnSuppPayAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppPayAddActionPerformed(evt);
            }
        });

        btnSuppPayCansel.setText("Cansel");
        btnSuppPayCansel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppPayCanselActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnSuppPayAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnSuppPayCansel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuppPayAdd)
                    .addComponent(btnSuppPayCansel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuppPayCanselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppPayCanselActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuppPayCanselActionPerformed

    private void btnSuppPayAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppPayAddActionPerformed
       addNewPaymentToSupplier();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuppPayAddActionPerformed

    private void txtSuppPayInvNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuppPayInvNumActionPerformed
txtSuppPaySupplier.requestFocus();   // TODO add your handling code here:
    }//GEN-LAST:event_txtSuppPayInvNumActionPerformed

    private void txtSuppPaySupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuppPaySupplierActionPerformed
jDateSuppPayDate.requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_txtSuppPaySupplierActionPerformed

    private void jDateSuppPayDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateSuppPayDateKeyPressed
txtSuppPayAmount.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jDateSuppPayDateKeyPressed

    private void txtSuppPayAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuppPayAmountActionPerformed
txtSuppPayRemarks.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuppPayAmountActionPerformed

    private void txtSuppPayRemarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuppPayRemarksActionPerformed
btnSuppPayAdd.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuppPayRemarksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SupplierPayment dialog = new SupplierPayment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuppPayAdd;
    private javax.swing.JButton btnSuppPayCansel;
    private com.toedter.calendar.JDateChooser jDateSuppPayDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSuppPayAmount;
    private javax.swing.JTextField txtSuppPayInvNum;
    private javax.swing.JTextField txtSuppPayRemarks;
    private javax.swing.JTextField txtSuppPaySupplier;
    // End of variables declaration//GEN-END:variables
}
