/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SupplierPaymentUpdate.java
 *
 * Created on May 22, 2015, 8:47:53 PM
 */
package views.debtviews;

import controllers.PaymentSupplierController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.PaymentSupplier;

/**
 *
 * @author HP2000
 */
public class SupplierPaymentUpdate extends javax.swing.JDialog {

    private DefaultTableModel servicedtm;
    private PaymentSupplier paymentSupplier;
    /** Creates new form SupplierPaymentUpdate */
    
    
    public SupplierPaymentUpdate(java.awt.Frame parent, boolean modal,PaymentSupplier paymentSupplier) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.paymentSupplier = paymentSupplier;
        try {
            setValuesUpdate(paymentSupplier);
        } catch (ParseException parseException) {
        }
    
    
    }

    private SupplierPaymentUpdate(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    public void setValuesUpdate(PaymentSupplier pay) throws ParseException {
        txtUinvoiceNu.setText(pay.getInvoicenumber());
         txtUSupplier.setText(pay.getSupplier());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        jDateUDate.setDate(sdf.parse(pay.getDate()));
        txtUAmount.setText(pay.getAmount() + "");
        txtURemarks.setText(pay.getRemarks());
    }

public void updateSupplierToPayment() {
       try {
        String invoicenumber = txtUinvoiceNu.getText();
        String supplier = txtUSupplier.getText();
        String remarks = txtURemarks.getText();
        double amount = Double.parseDouble(txtUAmount.getText());
        Date d1 = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(jDateUDate.getDate());
        sdf.applyPattern("HH:mm:ss");
        String time = sdf.format(d1);

             if ("".equals(supplier) || supplier == null || supplier.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter supplier name.", "No supplier name", JOptionPane.ERROR_MESSAGE);
             } 
           
            else if (amount == 0) {
                JOptionPane.showMessageDialog(this, "Amount cannot be 0 or minus", "Wrong Amount", JOptionPane.ERROR_MESSAGE);
            }
            else {
                 PaymentSupplier payment = new PaymentSupplier();
                  payment.setSupplierID(paymentSupplier.getSupplierID());
                 payment.setInvoicenumber(invoicenumber);
                 payment.setSupplier(supplier);
                 payment.setDate(date);
                 payment.setAmount(amount);
                 payment.setRemarks(remarks);
                 
                                                           
                 int value = PaymentSupplierController.updateSupplierToPayment(payment);
                if (value > 0) {
                    JOptionPane.showMessageDialog(this, "Payment to supplier updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please check your values again.", "Error in values", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateUDate = new com.toedter.calendar.JDateChooser();
        txtUinvoiceNu = new javax.swing.JTextField();
        txtUAmount = new javax.swing.JTextField();
        txtURemarks = new javax.swing.JTextField();
        txtUSupplier = new javax.swing.JTextField();
        btnUupdate = new javax.swing.JButton();
        btnUCansel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update supplier Payment");

        jLabel1.setText("Invoice Number");

        jLabel2.setText("Supplier");

        jLabel3.setText("Amount: (Rs)");

        jLabel4.setText("Date");

        jLabel5.setText("Remarks");

        jDateUDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateUDateKeyPressed(evt);
            }
        });

        txtUinvoiceNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUinvoiceNuActionPerformed(evt);
            }
        });

        txtUAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUAmountActionPerformed(evt);
            }
        });

        txtURemarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURemarksActionPerformed(evt);
            }
        });

        txtUSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txtUinvoiceNu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateUDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUAmount, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtURemarks, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUinvoiceNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtUSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jDateUDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtURemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnUupdate.setText("Update");
        btnUupdate.setToolTipText("");
        btnUupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUupdateActionPerformed(evt);
            }
        });

        btnUCansel.setText("Cansel");
        btnUCansel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUCanselActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnUupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnUCansel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUupdate)
                    .addComponent(btnUCansel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUupdateActionPerformed
       updateSupplierToPayment();        // TODO add your handling code here:
    }//GEN-LAST:event_btnUupdateActionPerformed

    private void btnUCanselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUCanselActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnUCanselActionPerformed

    private void txtUinvoiceNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUinvoiceNuActionPerformed
txtUSupplier.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtUinvoiceNuActionPerformed

    private void txtUSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUSupplierActionPerformed
jDateUDate.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtUSupplierActionPerformed

    private void jDateUDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateUDateKeyPressed
txtUAmount.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jDateUDateKeyPressed

    private void txtUAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUAmountActionPerformed
     txtURemarks.requestFocus();   // TODO add your handling code here:
    }//GEN-LAST:event_txtUAmountActionPerformed

    private void txtURemarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURemarksActionPerformed
btnUupdate.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtURemarksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SupplierPaymentUpdate dialog = new SupplierPaymentUpdate(new javax.swing.JFrame(),true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUCansel;
    private javax.swing.JButton btnUupdate;
    private com.toedter.calendar.JDateChooser jDateUDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtUAmount;
    private javax.swing.JTextField txtURemarks;
    private javax.swing.JTextField txtUSupplier;
    private javax.swing.JTextField txtUinvoiceNu;
    // End of variables declaration//GEN-END:variables
}
