/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views.serviceviews;

import controllers.ServiceController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import models.Service;

/**
 *
 * @author Iresha Lakmali
 *
 */
public class ServicePanel extends javax.swing.JPanel {

    private DefaultTableModel servicedtm;

    /**
     * Creates new form SalesPanel
     */
    public ServicePanel() {
        initComponents();
        // btnUpdateService1.setVisible(false);

        servicedtm = (DefaultTableModel) tblServices.getModel();
        try {
            ServiceController.loadAllServices(servicedtm);
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }
    }

    public void checkServiceButtons() {
        int selectedRows[] = tblServices.getSelectedRows();

        if (selectedRows.length > 0) {
            btnDeleteService.setEnabled(true);
            btnUpdateService1.setEnabled(true);
        } else {
            btnDeleteService.setEnabled(false);
            btnUpdateService1.setEnabled(false);
        }
    }

    public void deleteService() {
        int[] selectedRows = tblServices.getSelectedRows();

        try {
            while (selectedRows.length > 0) {
                int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this service?", "Delete", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                int value = 0;
                if (option == 0) {
                    Service service = new Service();
                    service.setServiceId(Integer.parseInt((String) tblServices.getValueAt(selectedRows[0], 0)));
                    value = ServiceController.deleteService(service);
                    servicedtm.removeRow(selectedRows[0]);
                    selectedRows = tblServices.getSelectedRows();

                    if (value > 0) {
                        JOptionPane.showMessageDialog(this, "Service successfuly deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
                        checkServiceButtons();
                    }
                } else {
                    tblServices.clearSelection();
                    checkServiceButtons();
                    break;

                }

            }
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (SQLException sQLException) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_search_service = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnDeleteService = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnUpdateService1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(941, 653));

        tblServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Service No", "Description", "Service Cost", "Service Charge", "Remarks", "Registered Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblServicesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblServices);
        tblServices.getColumnModel().getColumn(0).setMinWidth(0);
        tblServices.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblServices.getColumnModel().getColumn(0).setMaxWidth(0);

        jLabel1.setText("Search :");

        txt_search_service.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_serviceKeyReleased(evt);
            }
        });

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDeleteService.setText("Delete");
        btnDeleteService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteServiceActionPerformed(evt);
            }
        });

        jButton4.setText("Search");

        btnUpdateService1.setText("Update");
        btnUpdateService1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateService1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_search_service, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 436, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 620, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateService1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteService, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteService, btnUpdateService1, jButton1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_search_service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteService)
                    .addComponent(btnUpdateService1)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDeleteService, btnUpdateService1, jButton1});

        jTabbedPane1.addTab("All Services", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            NewService newService = new NewService(null, true);
            newService.setVisible(true);
            ServiceController.loadAllServices(servicedtm);
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (SQLException sQLException) {
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_search_serviceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_serviceKeyReleased
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(servicedtm);
        tblServices.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txt_search_service.getText()));
    }//GEN-LAST:event_txt_search_serviceKeyReleased

    private void tblServicesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicesMousePressed
        checkServiceButtons();
    }//GEN-LAST:event_tblServicesMousePressed

    private void btnDeleteServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteServiceActionPerformed
        deleteService();
    }//GEN-LAST:event_btnDeleteServiceActionPerformed

    private void btnUpdateService1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateService1ActionPerformed

        int row = tblServices.getSelectedRow();
        int supplierID = Integer.parseInt(tblServices.getValueAt(row, 0).toString());
        System.out.println(supplierID);
        int val0 = Integer.parseInt(tblServices.getValueAt(row, 0).toString());
        String val1 = tblServices.getValueAt(row, 1).toString();
        String val2 = tblServices.getValueAt(row, 2).toString();
        String val3 = tblServices.getValueAt(row, 3).toString();
        String val4 = tblServices.getValueAt(row, 4).toString();
        String val5 = tblServices.getValueAt(row, 5).toString();
        Service service = new Service();

        service.setServiceId(val0);
        service.setServiceCode(val1);
        service.setServiceName(val2);
        service.setServiceCost(val3);
        service.setServicecharge(val4);
        service.setServiceRemark(val5);
        UpdateService updateService = new UpdateService(null, true);
        updateService.setUpdateService(service);
        updateService.setVisible(true);
        try {
            ServiceController.loadAllServices(servicedtm);
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }


    }//GEN-LAST:event_btnUpdateService1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteService;
    private javax.swing.JButton btnUpdateService1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblServices;
    private javax.swing.JTextField txt_search_service;
    // End of variables declaration//GEN-END:variables
}
