/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.suggest;

import controllers.SuggestController;
import java.io.FileWriter;
import java.io.IOException;
import java.net.MalformedURLException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import models.Suggest;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author insaf
 */
public class DetailDialog extends javax.swing.JDialog {

    DefaultTableModel dtm;
    DefaultTableModel sugg;
    public int purchase_order_id;
    private Timer timer;
    public JSONArray obj = new JSONArray();
    public double discounts;
    SuggestPanel suggestPanel;

    /**
     * Creates new form detailDialog
     */
    public DetailDialog(java.awt.Frame parent, boolean modal, int pur_order, DefaultTableModel sugg, double discounts, String vat, SuggestPanel suggestPanel) {
        super(parent, modal);
        initComponents();
        purchase_order_id = pur_order;
        this.sugg = sugg;
        this.discounts = discounts;
        discount_field.setText(String.valueOf(discounts));
        vat_field.setText(vat);
        this.suggestPanel = suggestPanel;

        dtm = (DefaultTableModel) suggestOrderDetailTable.getModel();
        getSuggestOrderDetail(pur_order);
        counting_method();

        /*timer = new Timer(3000, new ActionListener() {

         @Override
         public void actionPerformed(ActionEvent e) {
               
         }
         });*/
        //imagepanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        suggestOrderDetailTable = new javax.swing.JTable();
        totalLabel = new javax.swing.JLabel();
        acceptorderbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        changebutton = new javax.swing.JButton();
        add_more = new javax.swing.JButton();
        remove_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tawd = new javax.swing.JTextField();
        tawv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        discount_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vat_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Purchase Order");
        setPreferredSize(new java.awt.Dimension(2000, 400));
        setType(java.awt.Window.Type.POPUP);

        suggestOrderDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "detailid", "Part Number", "Description", "Qty", "Unit Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(suggestOrderDetailTable);
        if (suggestOrderDetailTable.getColumnModel().getColumnCount() > 0) {
            suggestOrderDetailTable.getColumnModel().getColumn(0).setMinWidth(0);
            suggestOrderDetailTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        totalLabel.setFont(new java.awt.Font("Droid Sans", 0, 36)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        acceptorderbutton.setBackground(new java.awt.Color(0, 255, 102));
        acceptorderbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        acceptorderbutton.setText("Accept Order");
        acceptorderbutton.setToolTipText("click for accept");
        acceptorderbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptorderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptorderbuttonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Reject");
        jButton1.setToolTipText("click for reject");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        changebutton.setText("Change Qty");
        changebutton.setToolTipText("chage qty");
        changebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebuttonActionPerformed(evt);
            }
        });

        add_more.setText("Add More");
        add_more.setToolTipText("add new parts");
        add_more.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_moreActionPerformed(evt);
            }
        });

        remove_button.setText("Remove");
        remove_button.setToolTipText("remove parts");
        remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Total Amount With Discount");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Total Amount With Vat");

        tawd.setEditable(false);
        tawd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tawv.setEditable(false);
        tawv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tawv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Dealer Discount(%)");

        discount_field.setEditable(false);
        discount_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Vat(%)");

        vat_field.setEditable(false);
        vat_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vat_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vat_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(changebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_more, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acceptorderbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tawv, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tawd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(discount_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vat_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {acceptorderbutton, changebutton, jButton1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add_more, remove_button});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(discount_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vat_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tawd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tawv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acceptorderbutton)
                        .addComponent(jButton1)
                        .addComponent(changebutton)
                        .addComponent(add_more)
                        .addComponent(remove_button))
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptorderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptorderbuttonActionPerformed

        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Are you sure you want Accept this order ?");
        if (showConfirmDialog == 0) {
            try {
                int row_count = dtm.getRowCount();
                for (int i = 0; i < row_count; i++) {
                    String part_no = String.valueOf(dtm.getValueAt(i, 1));
                    String qty = String.valueOf(dtm.getValueAt(i, 3));
                    String unit_price = String.valueOf(dtm.getValueAt(i, 4));

                    JSONObject a = new JSONObject();
                    a.put("part_no", part_no);
                    a.put("qty", qty);
                    a.put("unit_price", unit_price);
                    obj.put(a);

                }
                String json = obj.toString();

                try {
                    double tawd_double = Double.parseDouble(tawd.getText());
                    double tawv_double = Double.parseDouble(tawv.getText());
                    String result = SuggestController.accept_purchase_order(purchase_order_id, json, tawd_double, tawv_double);
                    System.out.println("result:"+result);
                    int res = Integer.parseInt(result);
                    if (res > 0) {
                        JOptionPane.showMessageDialog(this, "Successfully Sent");
                        this.dispose();
                        suggestPanel.send();
                    } else {
                        JOptionPane.showMessageDialog(this, "Not Sent Try Again..");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(DetailDialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DetailDialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(DetailDialog.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (JSONException ex) {
                Logger.getLogger(DetailDialog.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            System.out.println("No");
        }


    }//GEN-LAST:event_acceptorderbuttonActionPerformed

    private void changebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebuttonActionPerformed
        int selectedRowCount = suggestOrderDetailTable.getSelectedRowCount();
        if (selectedRowCount > 0) {
            int selected_row = suggestOrderDetailTable.getSelectedRow();

            ChangeForm changeForm = new ChangeForm(null, true, dtm, selected_row, this);
            changeForm.setLocationRelativeTo(this);
            changeForm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No Selected Item");
        }

    }//GEN-LAST:event_changebuttonActionPerformed

    private void remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_buttonActionPerformed
        int selectedRowCount = suggestOrderDetailTable.getSelectedRowCount();
        if (selectedRowCount > 0) {
            int selected_row = suggestOrderDetailTable.getSelectedRow();
            System.out.println(selected_row);
            int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Are you sure you want remove this");
            if (showConfirmDialog == 0) {
                dtm.removeRow(selected_row);
                counting_method();
//            try {
//                String part_no = String.valueOf(dtm.getValueAt(selected_row, 1));
//
//                JSONObject a = new JSONObject();
//                a.put("name", "foo");
//                a.put("num", new Integer(100));
//                a.put("balance", new Double(1000.21));
//                a.put("is_vip", new Boolean(true));
//
//                JSONObject b = new JSONObject();
//                b.put("name", "foo");
//                b.put("num", new Integer(100));
//                b.put("balance", new Double(1000.21));
//                b.put("is_vip", new Boolean(true));
//                obj.put(a);
//                obj.put(b);
//                System.out.println(obj);
//               
//                //  System.out.println(dtm.getRowCount());
//                //System.out.println(dtm.getValueAt(selected_row, 1));
//            } catch (JSONException ex) {
//                Logger.getLogger(DetailDialog.class.getName()).log(Level.SEVERE, null, ex);
//            }

            } else {
                System.out.println("No");
            }

        } else {
            JOptionPane.showMessageDialog(this, "No Selected Item");
        }

    }//GEN-LAST:event_remove_buttonActionPerformed

    private void add_moreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_moreActionPerformed
        AddMore addMore = new AddMore(null, true, dtm, this);
        addMore.setLocationRelativeTo(this);
        addMore.setVisible(true);
    }//GEN-LAST:event_add_moreActionPerformed

    private void vat_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vat_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vat_fieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Reject This Order ?");
       
       
        if (showConfirmDialog == 0) {
           ReasonForm reasonForm=new ReasonForm(null,true,purchase_order_id,this,suggestPanel);
           reasonForm.setLocationRelativeTo(this);
           reasonForm.setVisible(true);
        } else {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DetailDialog dialog = new DetailDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptorderbutton;
    private javax.swing.JButton add_more;
    private javax.swing.JButton changebutton;
    private javax.swing.JTextField discount_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton remove_button;
    private javax.swing.JTable suggestOrderDetailTable;
    private javax.swing.JTextField tawd;
    private javax.swing.JTextField tawv;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField vat_field;
    // End of variables declaration//GEN-END:variables

    private void getSuggestOrderDetail(int pur_order) {
        try {
            SuggestController.getSuggestOrderItems(pur_order, dtm, totalLabel);
        } catch (IOException ex) {
            Logger.getLogger(DetailDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(DetailDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void counting_method() {
        int rowCount = dtm.getRowCount();
        double total = 0;
        for (int i = 0; i < rowCount; i++) {
            double amount = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 5)));
            total = total + amount;
            System.out.println(amount);
        }
        double discount = Double.parseDouble(discount_field.getText());
        double vat = Double.parseDouble(vat_field.getText());
        double discount_amount = total * discount / 100;
        double vat_amount = total * vat / 100;
        tawd.setText(String.format("%.2f", (total) - (discount_amount))); 
        tawv.setText(String.format("%.2f", (total) - (discount_amount) + vat_amount));
    }
}
