/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.supplierviews;

import controllers.SupplierController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import models.Supplier;

/**
 *
 * @author Dinesh
 */
public class SupplierPanel extends javax.swing.JPanel {

    private DefaultTableModel supplierDtm;
    private TableRowSorter<TableModel> supplierSorter;

    /**
     * Creates new form SupplierPanel
     */
    public SupplierPanel() {
        initComponents();
        supplierDtm = (DefaultTableModel) tblAllSuppliers.getModel();
        checkSupplierButtons();
        try {
            SupplierController.loadAllSuppliers(supplierDtm);
        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        }
    }

    public void deleteSupplier() {
        int[] selectedRows = tblAllSuppliers.getSelectedRows();

        try {
            while (selectedRows.length > 0) {
                int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this supplier?", "Delete", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                int value = 0;
                if (option == 0) {
                    Supplier supplier = new Supplier(Integer.parseInt((String) tblAllSuppliers.getValueAt(selectedRows[0], 0)));
                    value = SupplierController.deleteSupplier(supplier);
                    supplierDtm.removeRow(selectedRows[0]);
                    selectedRows = tblAllSuppliers.getSelectedRows();

                    if (value > 0) {
                        JOptionPane.showMessageDialog(this, "This supplier has been successfuly deleted", "Succeed", JOptionPane.INFORMATION_MESSAGE);
                        checkSupplierButtons();
                    }
                } else {
                    tblAllSuppliers.clearSelection();
                    checkSupplierButtons();
                    break;

                }

            }
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (SQLException sQLException) {
        }
    }

    public void checkSupplierButtons() {
        int selectedRows[] = tblAllSuppliers.getSelectedRows();

        if (selectedRows.length > 0) {
            btnDeleteSupplier.setEnabled(true);
            btnUpdateSupplier.setEnabled(true);
        } else {
            btnDeleteSupplier.setEnabled(false);
            btnUpdateSupplier.setEnabled(false);
        }
    }

    public void checkDimoSupplier() {

        int row = tblAllSuppliers.getSelectedRow();
        int supplierID = Integer.parseInt(tblAllSuppliers.getValueAt(row, 0).toString());
        if (supplierID == 1) {
            btnDeleteSupplier.setEnabled(false);
            btnUpdateSupplier.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllSuppliers = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnNewSupplier = new javax.swing.JButton();
        btnDeleteSupplier = new javax.swing.JButton();
        btnUpdateSupplier = new javax.swing.JButton();
        txtSearchSupplier = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        tblAllSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Added Date", "Address", "Phone No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAllSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAllSuppliersMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblAllSuppliers);
        if (tblAllSuppliers.getColumnModel().getColumnCount() > 0) {
            tblAllSuppliers.getColumnModel().getColumn(0).setMinWidth(0);
            tblAllSuppliers.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblAllSuppliers.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnNewSupplier.setText("New");
        btnNewSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSupplierActionPerformed(evt);
            }
        });

        btnDeleteSupplier.setText("Delete");
        btnDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupplierActionPerformed(evt);
            }
        });

        btnUpdateSupplier.setText("Update");
        btnUpdateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 60, Short.MAX_VALUE)
                .addComponent(btnNewSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateSupplier))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteSupplier, btnNewSupplier, btnUpdateSupplier});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpdateSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnNewSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDeleteSupplier, btnNewSupplier, btnUpdateSupplier});

        txtSearchSupplier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchSupplierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchSupplierFocusLost(evt);
            }
        });
        txtSearchSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchSupplierKeyReleased(evt);
            }
        });

        jButton1.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 412, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSupplierActionPerformed
        try {
            new NewSupplier(null, true).setVisible(true);
            SupplierController.loadAllSuppliers(supplierDtm);
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnNewSupplierActionPerformed

    private void btnDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplierActionPerformed
        deleteSupplier();
    }//GEN-LAST:event_btnDeleteSupplierActionPerformed

    private void btnUpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSupplierActionPerformed
        int selectedID = Integer.parseInt(tblAllSuppliers.getValueAt(tblAllSuppliers.getSelectedRow(), 0).toString());
        new UpdateSupplier(supplierDtm, selectedID).setVisible(true);
    }//GEN-LAST:event_btnUpdateSupplierActionPerformed

    private void tblAllSuppliersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllSuppliersMousePressed
        checkSupplierButtons();
        checkDimoSupplier();
    }//GEN-LAST:event_tblAllSuppliersMousePressed

    private void txtSearchSupplierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchSupplierFocusLost
        txtSearchSupplier.setText("Search Supplier..");
    }//GEN-LAST:event_txtSearchSupplierFocusLost

    private void txtSearchSupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchSupplierKeyReleased
        tblAllSuppliers.setRowSorter(supplierSorter);
        supplierSorter = new TableRowSorter<TableModel>(supplierDtm);
        supplierSorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtSearchSupplier.getText()));
    }//GEN-LAST:event_txtSearchSupplierKeyReleased

    private void txtSearchSupplierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchSupplierFocusGained
       txtSearchSupplier.setText("");
    }//GEN-LAST:event_txtSearchSupplierFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnNewSupplier;
    private javax.swing.JButton btnUpdateSupplier;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAllSuppliers;
    private javax.swing.JTextField txtSearchSupplier;
    // End of variables declaration//GEN-END:variables
}
