/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views.salesorderviws;

import controllers.SalesCounterController;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.SalesCounter;

/**
 *
 * @author user-pc
 */
public class SalesDiscount extends javax.swing.JFrame {
   private static int employeeID;
  // 1private SalesOrderPanel sop;
   private DefaultTableModel  savedPartsDtm;
  //private DefaultTableModel orderItemDtm;
   public double amount;
   public double discount;
    /**
     * Creates new form SalesDiscount
     */
    public SalesDiscount(int empId) {
        /*1
        sop = new SalesOrderPanel();
        initComponents();
        this.sop = sop;*/
        //1savedPartsDtm = (DefaultTableModel) sop.getTblSavedOrderDetails().getModel();
      // orderItemDtm = (DefaultTableModel) sop.getTblOrderContains().getModel();
        this.employeeID = empId;
        jdate_salescounter.setDate(new Date());
    }
    
    public SalesDiscount(int empId, double amount,double discount) {
        
     //1   sop = new SalesOrderPanel();
        initComponents();
        this.amount = amount;
        txt_partAmount.setText("" +amount);
        
        this.discount = discount;
        txt_dis.setText("" +discount);
      //1  this.sop = sop;
      //1  savedPartsDtm= (DefaultTableModel) sop.getTblSavedOrderDetails().getModel();
      //orderItemDtm = (DefaultTableModel) sop.getTblOrderContains().getModel();
        this.employeeID = empId;
        jdate_salescounter.setDate(new Date());
    }
    

    
     public void addSalesDiscount() throws ClassNotFoundException, SQLException {
    try{
           Date d1 = new Date();
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          String addedDate = sdf.format(d1);
          String date = sdf.format(jdate_salescounter.getDate());
          sdf.applyPattern("HH:mm:ss");
          String addedTime = sdf.format(d1);   
         
      
         double amount= Double.parseDouble(txt_partAmount.getText());
         double discount= Double.parseDouble(txt_dis.getText());
         double discountAmount=amount*(discount/100);
         String commision=Double.toString(discountAmount);
         txt_commision.setText( commision);
         
          
          
      //  String commision= txt_commision.getText();
        if (date == "" || date == null || date.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a date", "Empty date", JOptionPane.ERROR_MESSAGE);
        } 
        else{    
         SalesCounter salesCounter  = new SalesCounter(employeeID,addedDate,addedTime,date,amount,discount,commision);
            int value=SalesCounterController.addNewSales(salesCounter) ;
            if (value> 0) {
            JOptionPane.showMessageDialog(this, " sales counter discount added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
               dispose();    
            }
         }
                
          }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please check your values again.", "Error in values", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jdate_salescounter = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_partAmount = new javax.swing.JTextField();
        txt_dis = new javax.swing.JTextField();
        txt_commision = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_cancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("sales counter commision");

        jLabel1.setText("Date  :");

        jLabel2.setText("Part Amount :");

        jLabel3.setText("Commision % :");

        jLabel4.setText("Employee Commision :");

        txt_partAmount.setEditable(false);

        txt_dis.setEditable(false);
        txt_dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_disActionPerformed(evt);
            }
        });
        txt_dis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_disKeyTyped(evt);
            }
        });

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_cancle.setText("Cancle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_add)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_partAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(txt_dis)
                        .addComponent(txt_commision))
                    .addComponent(jdate_salescounter, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdate_salescounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_partAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_commision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_cancle))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       try{
              
           addSalesDiscount();  
         
                   
         }catch(Exception e){
             e.printStackTrace();
         } // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_disActionPerformed
//         double amount= Double.parseDouble(txt_partAmount.getText());
//         double discount= Double.parseDouble(txt_dis.getText());
//        double discountAmount=amount*(discount/100);
//         String commision=Double.toString(discountAmount);
//         txt_commision.setText( commision);         // TODO add your handling code here:
    }//GEN-LAST:event_txt_disActionPerformed

    private void txt_disKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_disKeyTyped
      char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }           // TODO a        // TODO add your handling code here:
    }//GEN-LAST:event_txt_disKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesDiscount(employeeID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser jdate_salescounter;
    private javax.swing.JTextField txt_commision;
    private javax.swing.JTextField txt_dis;
    private javax.swing.JTextField txt_partAmount;
    // End of variables declaration//GEN-END:variables
}
