/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.salesorderviws;

import controllers.ServiceController;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import views.serviceviews.NewService;

/**
 *
 * @author shdinesh.99
 */
public class SelectService extends javax.swing.JDialog {

    /**
     * Creates new form SelectService
     */
    private DefaultTableModel serviceDtm, orderServicesDtm;
    private boolean isForUpdate = false;

    public SelectService(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }

    public SelectService(java.awt.Frame parent, boolean modal, DefaultTableModel orderServicesDtm) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        serviceDtm = (DefaultTableModel) tblSelectService.getModel();
        this.orderServicesDtm = orderServicesDtm;
        try {
            ServiceController.loadAllServices(serviceDtm);
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (SQLException sQLException) {
        }
    }

    public SelectService(java.awt.Frame parent, boolean modal, DefaultTableModel orderServicesDtm, boolean isForUpdate) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        serviceDtm = (DefaultTableModel) tblSelectService.getModel();
        this.orderServicesDtm = orderServicesDtm;
        this.isForUpdate = isForUpdate;
        try {
            ServiceController.loadAllServices(serviceDtm);
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (SQLException sQLException) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void addNewServicesToTable() throws ClassNotFoundException, SQLException {
        //String custName = ((String) cmbSelectCustomer.getSelectedItem());
        int selectedRow = tblSelectService.getSelectedRow();
        String serviceNo = tblSelectService.getValueAt(selectedRow, 1).toString();
        String description = tblSelectService.getValueAt(selectedRow, 2).toString();
        int serviceID = Integer.parseInt(tblSelectService.getValueAt(selectedRow, 0).toString());
        double cost = Double.parseDouble(tblSelectService.getValueAt(selectedRow, 4).toString());
        double qty = Double.parseDouble(txtServiceQty.getText());
        
        
        double discount = 0.00;
        double discountAmount = 0.00;
        double amount = 0.00;
        int categoryID = 0;
        int mnemonic = 0;
        int discountType = 0;
        mnemonic = buttonGroup1.getSelection().getMnemonic();
        System.out.println(mnemonic);
        String doneBy = txtDoneBy.getText();
        if (mnemonic == 49) {
            discountType = 1;
            discount = Double.parseDouble(txtDiscount.getText());
            discountAmount = ((cost * qty) * discount / 100);
            amount = (cost * qty) - discountAmount;
        } else if (mnemonic == 50) {
            discount = Double.parseDouble(txtDiscountAmount.getText());
            discountAmount = discount;
            amount = (cost * qty) - discountAmount;
        } else {
            discount = 0.00;
            discountAmount = 0.00;
            amount = cost * qty;

        }
        if (serviceNo == null || serviceNo == "") {
            JOptionPane.showMessageDialog(this, "Please select a service to add", "Error in selection", JOptionPane.WARNING_MESSAGE);

        } else if (qty <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity cannot be 0 or less.", "Invalid quantity", JOptionPane.WARNING_MESSAGE);
        } else {
            Object obj[] = {serviceID, serviceNo, description, qty, String.format("%.2f", discountAmount), String.format("%.2f", cost), String.format("%.2f", amount), discountType, doneBy, String.format("%.2f", discount)};
            orderServicesDtm.addRow(obj);
            clearFields();
            dispose();
        }
    }

    public void addNewServicesToTableOnUpdate() throws ClassNotFoundException, SQLException {
        //String custName = ((String) cmbSelectCustomer.getSelectedItem());
        int selectedRow = tblSelectService.getSelectedRow();
        String serviceNo = tblSelectService.getValueAt(selectedRow, 1).toString();
        String description = tblSelectService.getValueAt(selectedRow, 2).toString();
        int serviceID = Integer.parseInt(tblSelectService.getValueAt(selectedRow, 0).toString());
        double cost = Double.parseDouble(tblSelectService.getValueAt(selectedRow, 4).toString());
        double qty = Double.parseDouble(txtServiceQty.getText());
        double discount = 0.00;
        double discountAmount = 0.00;
        double amount = 0.00;
        int categoryID = 0;
        int mnemonic = 0;
        int discountType = 0;
        mnemonic = buttonGroup1.getSelection().getMnemonic();
        System.out.println(mnemonic);
        String doneBy = txtDoneBy.getText();
        if (mnemonic == 49) {
            discountType = 1;
            discount = Double.parseDouble(txtDiscount.getText());
            discountAmount = ((cost * qty) * discount / 100);
            amount = (cost * qty) - discountAmount;
        } else if (mnemonic == 50) {
            discount = Double.parseDouble(txtDiscountAmount.getText());
            discountAmount = discount;
            amount = (cost * qty) - discountAmount;
        } else {
            discount = 0.00;
            discountAmount = 0.00;
            amount = cost * qty;

        }
        if (serviceNo == null || serviceNo == "") {
            JOptionPane.showMessageDialog(this, "Please select a service to add", "Error in selection", JOptionPane.WARNING_MESSAGE);

        } else if (qty <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity cannot be 0 or less.", "Invalid quantity", JOptionPane.WARNING_MESSAGE);
        } else {
            Object obj[] = {0, serviceID, serviceNo, description, qty, String.format("%.2f", discountAmount), String.format("%.2f", cost), String.format("%.2f", amount), discountType, doneBy, String.format("%.2f", discount), 1, 0};
            orderServicesDtm.addRow(obj);
            clearFields();
            dispose();
        }
    }

    private void clearFields() {
        txtDiscount.setText("0.00");
        txtDiscountAmount.setText("0");

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSelectService = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtServiceSearch = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        lblDiscount1 = new javax.swing.JLabel();
        rdbPercentage = new javax.swing.JRadioButton();
        txtDiscount = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        txtDiscountAmount = new javax.swing.JTextField();
        txtServiceQty = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDoneBy = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All Services");
        setResizable(false);

        tblSelectService.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        tblSelectService.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblSelectService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Service No.", "Description", "Service Cost (Rs.)", "Service Charge (Rs.)", "Remarks", "added date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSelectService.setRowHeight(20);
        tblSelectService.setRowMargin(2);
        tblSelectService.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSelectService.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSelectServiceKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblSelectService);
        if (tblSelectService.getColumnModel().getColumnCount() > 0) {
            tblSelectService.getColumnModel().getColumn(0).setMinWidth(0);
            tblSelectService.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblSelectService.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSelectService.getColumnModel().getColumn(6).setMinWidth(0);
            tblSelectService.getColumnModel().getColumn(6).setPreferredWidth(0);
            tblSelectService.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        txtServiceSearch.setText("Search...");
        txtServiceSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceSearchActionPerformed(evt);
            }
        });
        txtServiceSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtServiceSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtServiceSearchFocusLost(evt);
            }
        });
        txtServiceSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServiceSearchKeyReleased(evt);
            }
        });

        jButton3.setText("New Service");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtServiceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblDiscount1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblDiscount1.setText("Discount :");

        buttonGroup1.add(rdbPercentage);
        rdbPercentage.setMnemonic('1');
        rdbPercentage.setSelected(true);
        rdbPercentage.setText("%");
        rdbPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPercentageActionPerformed(evt);
            }
        });

        txtDiscount.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtDiscount.setText("0.00");
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        txtDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiscountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiscountFocusLost(evt);
            }
        });
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountKeyReleased(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setMnemonic('2');
        jRadioButton1.setText("Amount");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        txtDiscountAmount.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtDiscountAmount.setText("0");
        txtDiscountAmount.setEnabled(false);
        txtDiscountAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountAmountActionPerformed(evt);
            }
        });
        txtDiscountAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiscountAmountFocusGained(evt);
            }
        });
        txtDiscountAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountAmountKeyReleased(evt);
            }
        });

        txtServiceQty.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtServiceQty.setText("0");
        txtServiceQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceQtyActionPerformed(evt);
            }
        });
        txtServiceQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtServiceQtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtServiceQtyFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Quantity :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Done by:");

        txtDoneBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDoneBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoneByActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblDiscount1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(rdbPercentage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtServiceQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiscountAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDoneBy, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiscount, txtDiscountAmount});

        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtServiceQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiscount1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbPercentage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(txtDiscountAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoneBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButton1, lblDiscount1, rdbPercentage, txtDiscount, txtDiscountAmount, txtDoneBy, txtServiceQty});

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSelectServiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSelectServiceKeyReleased
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ENTER) {
            tblSelectService.requestFocus(false);
            tblSelectService.changeSelection(tblSelectService.getSelectedRow() - 1, 0, false, false);
            txtServiceQty.requestFocus();
        }
    }//GEN-LAST:event_tblSelectServiceKeyReleased

    private void txtServiceSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceSearchActionPerformed

    private void txtServiceSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtServiceSearchFocusGained
        txtServiceSearch.setText("");
    }//GEN-LAST:event_txtServiceSearchFocusGained

    private void txtServiceSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtServiceSearchFocusLost
        txtServiceSearch.setText("Search...");
    }//GEN-LAST:event_txtServiceSearchFocusLost

    private void txtServiceSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServiceSearchKeyReleased
        try {
            final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(serviceDtm);
            tblSelectService.setRowSorter(sorter);
            sorter.setRowFilter(RowFilter.regexFilter(("(?i)" + txtServiceSearch.getText())));
            int keyCode = evt.getKeyCode();

            if (keyCode == KeyEvent.VK_DOWN) {
                tblSelectService.requestFocus();
                tblSelectService.changeSelection(0, 0, false, false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtServiceSearchKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            NewService newService = new NewService(null, true);
            newService.setVisible(true);
            ServiceController.loadAllServices(serviceDtm);
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (SQLException sQLException) {
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void rdbPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPercentageActionPerformed
        txtDiscount.setEnabled(true);
        txtDiscount.selectAll();
        txtDiscountAmount.setText("0");
        txtDiscountAmount.setEnabled(false);
    }//GEN-LAST:event_rdbPercentageActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        txtDoneBy.requestFocus();
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void txtDiscountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscountFocusGained
        txtDiscount.selectAll();
    }//GEN-LAST:event_txtDiscountFocusGained

    private void txtDiscountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscountFocusLost

    }//GEN-LAST:event_txtDiscountFocusLost

    private void txtDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyReleased
        //ValidateValues.validateTextFieldForNumber(txtDiscount);

    }//GEN-LAST:event_txtDiscountKeyReleased

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        txtDiscount.setText("0.00");
        txtDiscount.setEnabled(false);
        txtDiscountAmount.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtDiscountAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountAmountActionPerformed
        //btnAddToTable.doClick();
    }//GEN-LAST:event_txtDiscountAmountActionPerformed

    private void txtDiscountAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscountAmountFocusGained
        txtDiscountAmount.selectAll();
    }//GEN-LAST:event_txtDiscountAmountFocusGained

    private void txtDiscountAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountAmountKeyReleased
        // ValidateValues.validateTextFieldForNumber(txtDiscountAmount);

    }//GEN-LAST:event_txtDiscountAmountKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (!isForUpdate) {
                addNewServicesToTable();

            } else if (isForUpdate) {
                addNewServicesToTableOnUpdate();
            }
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDoneByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoneByActionPerformed
        btnAdd.doClick();
    }//GEN-LAST:event_txtDoneByActionPerformed

    private void txtServiceQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtServiceQtyFocusGained
        txtServiceQty.selectAll();
    }//GEN-LAST:event_txtServiceQtyFocusGained

    private void txtServiceQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtServiceQtyFocusLost
        String val = txtServiceQty.getText();
        if (val.isEmpty() || val.equals(null)) {
            txtServiceQty.setText("0");
        }
    }//GEN-LAST:event_txtServiceQtyFocusLost

    private void txtServiceQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceQtyActionPerformed
        txtDiscount.requestFocus();
    }//GEN-LAST:event_txtServiceQtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectService dialog = new SelectService(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiscount1;
    private javax.swing.JRadioButton rdbPercentage;
    private javax.swing.JTable tblSelectService;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtDiscountAmount;
    private javax.swing.JTextField txtDoneBy;
    private javax.swing.JTextField txtServiceQty;
    private javax.swing.JTextField txtServiceSearch;
    // End of variables declaration//GEN-END:variables
}
